name: Test-Automation-Initiate
on: 
  workflow_run:
    workflows: [build-test-deploy]
    types: [completed]
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps: 
      - name: Trigger test automation
        uses: peter-evans/repository dispatch@v4
        with:
          token: ${{ secrets.TEST_AUTOMATION_REPO_ACCESS }}
          repository: sksGHubAcc/SeleniumAutomation
          event-type: trigger-test
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
      
      
  
  
